spring.application.name=aso.web.api
server.port=8080
server.servlet.context-path=/aso-web-api

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/aso.web
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update